# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nusii < Formula
  desc "CLI for the Nusii proposal software API"
  homepage "https://github.com/nusii/nusii-cli"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Nusii/nusii-cli/releases/download/v0.1.0/nusii_0.1.0_darwin_amd64.tar.gz"
      sha256 "7f6921cd26149d199999432d31f9dc4501cad3804d7c56eaf828cdf1ec817b60"

      define_method(:install) do
        bin.install "nusii"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Nusii/nusii-cli/releases/download/v0.1.0/nusii_0.1.0_darwin_arm64.tar.gz"
      sha256 "5fd743eb1dfac0137aec8a2556d86c6182cf74eba051fb60f5bb68afa3970274"

      define_method(:install) do
        bin.install "nusii"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Nusii/nusii-cli/releases/download/v0.1.0/nusii_0.1.0_linux_amd64.tar.gz"
      sha256 "a546a272c90a1f87047f384334c4fb8f2a0cc692699fed61a2b94b91d1a8180b"
      define_method(:install) do
        bin.install "nusii"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Nusii/nusii-cli/releases/download/v0.1.0/nusii_0.1.0_linux_arm64.tar.gz"
      sha256 "9ffbda3ca6de3caa442dc88a34ebcebf6cc1c868b645363c99fe01596f54f9fa"
      define_method(:install) do
        bin.install "nusii"
      end
    end
  end

  test do
    system "#{bin}/nusii", "version"
  end
end
