# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nusii < Formula
  desc "CLI for the Nusii proposal software API"
  homepage "https://github.com/nusii/nusii-cli"
  version "0.1.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Nusii/nusii-cli/releases/download/v0.1.1/nusii_0.1.1_darwin_amd64.tar.gz"
      sha256 "a4dd3a4de218b87758721d7f34ed2c966659fce9990ad0655a300ea4313aa350"

      define_method(:install) do
        bin.install "nusii"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Nusii/nusii-cli/releases/download/v0.1.1/nusii_0.1.1_darwin_arm64.tar.gz"
      sha256 "86978d15586a254cd12be4007156dc5971631a0cd77aa9f47fee4f9782eba8e9"

      define_method(:install) do
        bin.install "nusii"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Nusii/nusii-cli/releases/download/v0.1.1/nusii_0.1.1_linux_amd64.tar.gz"
      sha256 "2c0efe30d80045fbfc9dae54ede7dbc42b6f8905ed1222ab9e53409533b47ef1"
      define_method(:install) do
        bin.install "nusii"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Nusii/nusii-cli/releases/download/v0.1.1/nusii_0.1.1_linux_arm64.tar.gz"
      sha256 "e7e4286828af45ac5a3a3cfdfb21b3ba9676de4f8a905ffff6faf97a38a8b0cd"
      define_method(:install) do
        bin.install "nusii"
      end
    end
  end

  test do
    system "#{bin}/nusii", "version"
  end
end
